#!/bin/sh
# The next line is executed by /bin/sh, but not Tcl \
exec tclsh $0 ${1+"$@"}

# Usage: regression [test1 [test2...]]
# Where test1 is all or the name of a tcl script in /test
# Wildcard matching with '*' and '?' in test names is supported.

# Directory containing tests.
set test_dir [file dirname [file normalize [info script]]]
set openroad_dir [file dirname [file dirname [file dirname [file dirname $test_dir]]]]

source [file join $openroad_dir "test" "regression.tcl"]
source [file join $test_dir "regression_tests.tcl"]

exec mkdir -p [file join $test_dir "results/utility"]

regression_main


# Local Variables:
# mode:tcl
# End: